name: 'fudge_group_project'
version: '1.0.0'
config-version: 2

profile: 'fudge_group_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Global model config
models:
  fudge_group_project:
    +materialized: table
    database: analytics
    +schema: FUDGECOMPANIES
    +custom_schema: ""

    fudgemart:
      +materialized: table

    fudgeflix:
      +materialized: table
