name: 'fudge_group_project'
version: '1.0.0'
config-version: 2

profile: 'fudge_group_project'

model-paths:    ["models"]
analysis-paths: ["analyses"]
test-paths:     ["tests"]
seed-paths:     ["seeds"]
macro-paths:    ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  # this key must exactly match your project name
  fudge_group_project:
    +materialized: table       # default materialization
    database: analytics        # target database in Snowflake
    +schema: FUDGECOMPANIES    # target schema in Snowflake
