name: 'fudge_group_project'
version: '1.0.0'
config-version: 2

profile: 'fudge_group_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  fudge_group_project:
    +materialized: view

    fudgemart:
      +materialized: table
      database: analytics
      +schema: fudgemart_v3

    fudgeflix:
      +materialized: table
      database: analytics
      +schema: fudgeflix_v3
