version: 2

sources:

  # 1) conform ed date dimension
  - name: conformed                # this is what you call in your dim_date.sql
    database: raw                  # RAW database in Snowflake
    schema: conformed              # RAW.CONFORMED schema
    tables:
      - name: DateDimension        # RAW.CONFORMED.DateDimension

  # 2) FudgeFlix
  - name: fudgeflix_v3
    database: raw
    schema: fudgeflix_v3
    tables:
      - name: ff_accounts     # RAW.FUDGEFLIX_V3.FF_ACCOUNTS
      - name: ff_plans        # RAW.FUDGEFLIX_V3.FF_PLANS

  # 3) FudgeMart
  - name: fudgemart_v3
    database: raw
    schema: fudgemart_v3
    tables:
      - name: fm_customers    # RAW.FUDGEMART_V3.FM_CUSTOMERS
      - name: fm_products     # RAW.FUDGEMART_V3.FM_PRODUCTS
