
version: 2

sources:
  - name: conformed
    database: raw
    schema: conformed
    tables:
      - name: DateDimension

  - name: fudgeflix
    database: raw
    schema: fudgeflix_v3
    tables:
      - name: FF_ACCOUNTS
      - name: FF_ACCOUNT_BILLING
      - name: FF_ACCOUNT_TITLES
      - name: FF_TITLES
      - name: FF_CAST
      - name: FF_DIRECTORS
      - name: FF_PEOPLE
      - name: FF_TITLE_GENRES
      - name: FF_GENRES
      - name: FF_PLANS
      - name: FF_ZIPCODES

  - name: fudgemart
    database: raw
    schema: fudgemart_v3
    tables:
      - name: FM_CUSTOMERS
      - name: FM_ORDERS
      - name: FM_ORDER_DETAILS
      - name: FM_PRODUCTS
      - name: FM_EMPLOYEES
      - name: FM_EMPLOYEE_TIMESHEETS
      - name: FM_CREDITCARDS
      - name: FM_CUSTOMER_CREDITCARDS
      - name: FM_CUSTOMER_PRODUCT_REVIEWS
      - name: FM_DEPARTMENTS_LOOKUP
      - name: FM_JOBTITLES_LOOKUP
      - name: FM_VENDORS
      - name: FM_SHIPVIA_LOOKUP
