
name: 'fudge_warehouse'
version: '1.0.0'
config-version: 2

profile: 'fudge_warehouse'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  fudge_warehouse:
    +materialized: view  # default for any models not overridden

    fudgemart:
      +materialized: table
      database: analytics
      +schema: fudgemart_v3

    fudgeflix:
      +materialized: table
      database: analytics
      +schema: fudgeflix_v3
